version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - ruby/install:
          version: '2.7'
      - ruby/install-deps
      - ruby/rspec-test
      - run: gem build