version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'

    working_directory: ~/repo/leeloo
    steps:
      - checkout:
          path: ~/repo
      - ruby/install:
          version: '2.7'
      - run: bundle --version
      - ruby/install-deps:
          bundler-version: 2.1.2
      - ruby/rspec-test
      - run: gem build